version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:cached
    environment:
      - CI_ENV=development
      - DB_HOST=db
      - DB_NAME=${DB_NAME:-ci_db}
      - DB_USER=${DB_USER:-ci_user}
      - DB_PASS=${DB_PASS:-ci_pass}
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpass}
      MYSQL_DATABASE: ${DB_NAME:-ci_db}
      MYSQL_USER: ${DB_USER:-ci_user}
      MYSQL_PASSWORD: ${DB_PASS:-ci_pass}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpass}
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data:
